conditions: v1

dist: trusty
sudo: false
language: python

python:
- 3.6

stage: &stage_deploy_name upload new version of python package to PYPI (only for tagged commits)
if: tag IS present
install: skip
script: skip
deploy:
  provider: pypi
  on:
    all_branches: true
    tags: true
  user: patron-it-opencanary-bot
  password:
    secure: >-
      db/yRIpWp9+jjiOGbUPSUzf+snwgrq7h5j/qtd958mW/o0fafD8Bp7NkEJt8BaO7wMx8yh/uNsYCpiIPCuooHbzQ5piYQrm3K/zQpW6kQFgp0+NF14PUAhLCpTgzVv5jw6OsIZD5RryZCEHRS1EDeO5jFVTB0PpR5Q5xC8xV2MtMOBfkvKTs2nYgJDMbR5MRXETZ5ORGcEYqgVDcXUh4EGAVpNI7TGXWcmXqB47Qe0y3ONrG6QqRAZEmneZ498Rv9xACXyBRum2Er6v2ncZzBYAuQiRK2cDfp0d8lRUg5iSY1dKfJDegaDhwNuIhTz/PpsLeiDUWwl5a+UEsD9DBmNwGZvGdap8rh0GzNCUmN+e5EkxShYuGhi7JPlNuVduOzQO3exYqfKTb8HIw/9RB6jAmnhNWte8sQxXHIGuuakdDZkLncfWfGSAZSoTuLtmrGAVNVcsm6V//oiCd99ZbVkZckCNaJ9tR0Jmj41Na06oSgfNNUAqVwUsRvJWSh7+SnJZWfut7nO3/JVNozjema+ekjs/fmCNnRpNEfdnORSDYWa4KN7iblAaRnXd2ptKyCwof+X+jDSZaL8Y5iJ4kUDatmFlTQQJCt2bFuklC8OPX0wNOEfSr0cuh8tkIdZCqJd6FbHTJrPJJYHQ+a8Qg1ZLR7SRYOo84BrInWy/ahAQ=
  distributions: clean --all sdist bdist_wheel
  skip_cleanup: true
  skip_upload_docs: true

env:
  global:
    scrt:
      secure: >-
        db/yRIpWp9+jjiOGbUPSUzf+snwgrq7h5j/qtd958mW/o0fafD8Bp7NkEJt8BaO7wMx8yh/uNsYCpiIPCuooHbzQ5piYQrm3K/zQpW6kQFgp0+NF14PUAhLCpTgzVv5jw6OsIZD5RryZCEHRS1EDeO5jFVTB0PpR5Q5xC8xV2MtMOBfkvKTs2nYgJDMbR5MRXETZ5ORGcEYqgVDcXUh4EGAVpNI7TGXWcmXqB47Qe0y3ONrG6QqRAZEmneZ498Rv9xACXyBRum2Er6v2ncZzBYAuQiRK2cDfp0d8lRUg5iSY1dKfJDegaDhwNuIhTz/PpsLeiDUWwl5a+UEsD9DBmNwGZvGdap8rh0GzNCUmN+e5EkxShYuGhi7JPlNuVduOzQO3exYqfKTb8HIw/9RB6jAmnhNWte8sQxXHIGuuakdDZkLncfWfGSAZSoTuLtmrGAVNVcsm6V//oiCd99ZbVkZckCNaJ9tR0Jmj41Na06oSgfNNUAqVwUsRvJWSh7+SnJZWfut7nO3/JVNozjema+ekjs/fmCNnRpNEfdnORSDYWa4KN7iblAaRnXd2ptKyCwof+X+jDSZaL8Y5iJ4kUDatmFlTQQJCt2bFuklC8OPX0wNOEfSr0cuh8tkIdZCqJd6FbHTJrPJJYHQ+a8Qg1ZLR7SRYOo84BrInWy/ahAQ=
before_deploy:
- echo "${scrt:0:2}..${scrt:31}"

cache:
  pip: true
