conditions: v1
group: legacy

dist: trusty
sudo: false
language: python

python:
- 3.6

stage: &stage_deploy_name upload new version of python package to PYPI (only for tagged commits)
if: tag IS present
install: skip
script: skip
deploy:
  provider: pypi
  on:
    all_branches: true
    tags: true
  user: patron-it-opencanary-bot
  password:
    secure: "CJr5vEewpazymBDeetBGjkIxMmr4GuvvxbdI/bcAyS+wBdfY8jt1XTVL/Gd/b7vZ1awczAgaDF+AZGWu8JetjQdsBGe6vd5ZitXjOs/M7Vim6LKDvyKKE231i5I7SqVp4v7btNRIROV0CrEWzJLhg3VXdXR968DluyW120e2eDnjeDti5EjLgQfYfIoDZzWrvKVyAB9zLkjUE/5ark9JpD7a6y6JfiMkKGFLzAe55tQlgFxVKQYoxpzFofVucwGdl9rMlDUsvV8c6GP9vjesv21R8mfHo4gtoRTWci4yM+8JSHIUQnostP0mZ3e6LiC71C9OVfgUcFvG+3ikomDOTZDsnahn+YbU4SAgI6WAajjoLE24F/W/pkELxT9MKURfMMDwsUH7epIoC9NBjLK4sYwQQmv7WtlcyGbOVl3T5o/Hn9MwuYhfNqmyEKQTdrB6hxOm1kIUVNouBdKT9CBWCeUXogVuAI0cpCDNikecD8tHFNT7V5ECapuijozXSiRyrv24ygZG14HAiABjbAKVCGgWx7kdCzch13muMiUiSk2/sN1EMDzzAgK3StVSuKhA/ItZKkEOubKYl/stgaB0m4Wm55IeFFOD2wzHDgWbglDhlxFPYOzrogUEnV+digcerXbFTiB6WXB4wmr6hssDhWo7u90MF3gBOFV/BZkD7As="
  distributions: clean --all sdist bdist_wheel
  skip_cleanup: true
  skip_upload_docs: true

env:
  global:
    scrt:
      secure: "CJr5vEewpazymBDeetBGjkIxMmr4GuvvxbdI/bcAyS+wBdfY8jt1XTVL/Gd/b7vZ1awczAgaDF+AZGWu8JetjQdsBGe6vd5ZitXjOs/M7Vim6LKDvyKKE231i5I7SqVp4v7btNRIROV0CrEWzJLhg3VXdXR968DluyW120e2eDnjeDti5EjLgQfYfIoDZzWrvKVyAB9zLkjUE/5ark9JpD7a6y6JfiMkKGFLzAe55tQlgFxVKQYoxpzFofVucwGdl9rMlDUsvV8c6GP9vjesv21R8mfHo4gtoRTWci4yM+8JSHIUQnostP0mZ3e6LiC71C9OVfgUcFvG+3ikomDOTZDsnahn+YbU4SAgI6WAajjoLE24F/W/pkELxT9MKURfMMDwsUH7epIoC9NBjLK4sYwQQmv7WtlcyGbOVl3T5o/Hn9MwuYhfNqmyEKQTdrB6hxOm1kIUVNouBdKT9CBWCeUXogVuAI0cpCDNikecD8tHFNT7V5ECapuijozXSiRyrv24ygZG14HAiABjbAKVCGgWx7kdCzch13muMiUiSk2/sN1EMDzzAgK3StVSuKhA/ItZKkEOubKYl/stgaB0m4Wm55IeFFOD2wzHDgWbglDhlxFPYOzrogUEnV+digcerXbFTiB6WXB4wmr6hssDhWo7u90MF3gBOFV/BZkD7As="
before_deploy:
- echo "${scrt:0:2}..${scrt:31}"

cache:
  pip: true
