conditions: v1

dist: trusty
sudo: false
language: python

python:
- 3.6

stage: &stage_deploy_name upload new version of python package to PYPI (only for tagged commits)
if: tag IS present
install: skip
script: skip
deploy:
  provider: pypi
  on:
    all_branches: true
    tags: true
  user: patron-it-opencanary-bot
  password:
    secure: >-
      EW0jKaZBMbq099bJmo242M+36m9ZwCH7SDPiZ2xo/GD4o9pw17j0ApoqUSFVZ8boW9MO9UrJ2cbzQlsTS9xEM93yjncmHwiknYowulF73t0eHQ4hnqtI5lAU4wlwBzuso1QH0kp5w1ayuIikTl1K3cTKy3j842gxNc1v9wcP2MuNs0RqKSvk6dp8LprqpWHS1rHIymkly0Ub6HOAVgHIK1UoJMKIwxTFIH7xIQuuuXiZyaYhU9RHAYlHnHdh88XjWMu/LiEfNs/0WcnmqEIIoGJdhwtBubsRImhdiGjXdvelWv8TlzEDjH2FthQIn2HvF1oTZChps92Ni6O0iUWG6swwd9bQwfvXoI/4bp2zj6H35oD4aFyyFpzwqeBEshCPktk20PonOKRgeZdtpx7CN2qwxcyqnTSfAq+nmooCIRz4/TOe5LYvPcsWRVJAe8BcModsNfxmZbzMrCvYRAY0ldOj0525ScEvfMIbA5bGQFhAmwTJTPDNymRhOoaTFTP68vYqRxZ5PkQrFNkt8/wAQ38VaUbPIj5O2HP1peNka9XR5lqCbHm5SVY8q77D/oAXRey8eHtLV8VmpGcM+Y+VGDts+HwfM/9zk6zTO+oxk6YKUEMVDU5znxYKWzb+Eknf1DGAJ2qXvDyX6Xxgjov+JaVP5RZiNg1T9DqXh9g2Ov0=
  distributions: clean --all sdist bdist_wheel
  skip_cleanup: true
  skip_upload_docs: true

env:
  global:
    scrt:
      secure: >-
        EW0jKaZBMbq099bJmo242M+36m9ZwCH7SDPiZ2xo/GD4o9pw17j0ApoqUSFVZ8boW9MO9UrJ2cbzQlsTS9xEM93yjncmHwiknYowulF73t0eHQ4hnqtI5lAU4wlwBzuso1QH0kp5w1ayuIikTl1K3cTKy3j842gxNc1v9wcP2MuNs0RqKSvk6dp8LprqpWHS1rHIymkly0Ub6HOAVgHIK1UoJMKIwxTFIH7xIQuuuXiZyaYhU9RHAYlHnHdh88XjWMu/LiEfNs/0WcnmqEIIoGJdhwtBubsRImhdiGjXdvelWv8TlzEDjH2FthQIn2HvF1oTZChps92Ni6O0iUWG6swwd9bQwfvXoI/4bp2zj6H35oD4aFyyFpzwqeBEshCPktk20PonOKRgeZdtpx7CN2qwxcyqnTSfAq+nmooCIRz4/TOe5LYvPcsWRVJAe8BcModsNfxmZbzMrCvYRAY0ldOj0525ScEvfMIbA5bGQFhAmwTJTPDNymRhOoaTFTP68vYqRxZ5PkQrFNkt8/wAQ38VaUbPIj5O2HP1peNka9XR5lqCbHm5SVY8q77D/oAXRey8eHtLV8VmpGcM+Y+VGDts+HwfM/9zk6zTO+oxk6YKUEMVDU5znxYKWzb+Eknf1DGAJ2qXvDyX6Xxgjov+JaVP5RZiNg1T9DqXh9g2Ov0=
before_deploy:
- echo "${scrt:0:2}..${scrt:31}"

cache:
  pip: true
